foreign: es
threads: 12
pool_size: 40
helper_dir: /home/judah/corpus
train_dir: /home/judah/corpus/training
train_name: kde4.es-en
tune_dir:  /home/judah/corpus/tuning
tune_name: mongo-docs-tune.es-en
test_dir: /home/judah/corpus/testing
test_name: mongo-docs-test.es-en
moses_path: /home/judah/mosesdecoder
irstlm_path: /home/judah/irstlm-5.80.03
model_path: /home/judah/archive7
datamine_path: /home/judah/doctrans/demo/datamine.py
email: judah.schvimer@10gen.com
phrase_table_name: phrase-table.0-0.1.1 
reordering_name: reordering-table.0-0
order:
   - 3
smoothing:
   - improved-kneser-ney
score_options:
   - --GoodTuring
alignment : 
   - grow-diag-final-and
reordering_modeltype:
   - phrase
   - hier
reordering_orientation:
   - mslr
   - msd
reordering_directionality:
   - bidirectional
reordering_language:
   - fe
max_phrase_length:
   - 7
