foreign: es
threads: 12
pool_size: 40
helper_dir: /home/judah/corpus/helper
train_dir: /home/judah/corpus/run02
train_name: train.en-es
tune_dir:  /home/judah/corpus/run02
tune_name: tune.en-es
test_dir: /home/judah/corpus/run02
test_name: test.en-es
moses_path: /home/judah/mosesdecoder
irstlm_path: /home/judah/irstlm-5.80.03
model_path: /home/judah/archive10
datamine_path: /home/judah/doctrans/demo/datamine.py
email: judah.schvimer@10gen.com
phrase_table_name: phrase-table
reordering_name: reordering-table
order:
   - 3
smoothing:
   - improved-kneser-ney
score_options:
   - --GoodTuring
alignment : 
   - grow-diag-final-and
reordering_modeltype:
   - hier
reordering_orientation:
   - mslr
reordering_directionality:
   - bidirectional
reordering_language:
   - fe
max_phrase_length:
   - 7
