name: run00
foreign_language: es
corpus_language: en
sources:
    - file_name: t1
      file_path: sandbox/t1
      percent_train: 50
      percent_test: 30
      percent_tune: 20
    - file_name: t2
      file_path: sandbox/t2
      percent_train: 50
      percent_test: 30
      percent_tune: 20
source_contributions:
    train:
        - file_name: t1
          percent_of_corpus: 40
        - file_name: t2
          percent_of_corpus: 60
    test:
        - file_name: t1
          percent_of_corpus: 100
    tune:
        - file_name: t1
          percent_of_corpus: 90
        - file_name: t2
          percent_of_corpus: 10
